# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conversation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x05proto\"_\n\tUrlAnswer\x12\x0c\n\x04text\x18\x01 \x01(\t\x12!\n\x03url\x18\x02 \x03(\x0b\x32\x14.proto.UrlAnswer.Url\x1a!\n\x03Url\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"b\n\x10\x43onversationLink\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12)\n\x06\x62ranch\x18\x02 \x01(\x0b\x32\x17.proto.ConversationNodeH\x00\x42\x13\n\x11\x63onversation_link\"\xcf\x01\n\x10\x43onversationNode\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\x06\x61nswer\x18\x02 \x03(\x0b\x32\x1e.proto.ConversationNode.Answer\x12%\n\x04link\x18\x03 \x03(\x0b\x32\x17.proto.ConversationLink\x1aV\n\x06\x41nswer\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12!\n\x05links\x18\x02 \x01(\x0b\x32\x10.proto.UrlAnswerH\x00\x12\x0f\n\x05photo\x18\x03 \x01(\tH\x00\x42\x08\n\x06\x61nswer\"5\n\x0c\x43onversation\x12%\n\x04node\x18\x01 \x03(\x0b\x32\x17.proto.ConversationNodeb\x06proto3')



_URLANSWER = DESCRIPTOR.message_types_by_name['UrlAnswer']
_URLANSWER_URL = _URLANSWER.nested_types_by_name['Url']
_CONVERSATIONLINK = DESCRIPTOR.message_types_by_name['ConversationLink']
_CONVERSATIONNODE = DESCRIPTOR.message_types_by_name['ConversationNode']
_CONVERSATIONNODE_ANSWER = _CONVERSATIONNODE.nested_types_by_name['Answer']
_CONVERSATION = DESCRIPTOR.message_types_by_name['Conversation']
UrlAnswer = _reflection.GeneratedProtocolMessageType('UrlAnswer', (_message.Message,), {

  'Url' : _reflection.GeneratedProtocolMessageType('Url', (_message.Message,), {
    'DESCRIPTOR' : _URLANSWER_URL,
    '__module__' : 'conversation_pb2'
    # @@protoc_insertion_point(class_scope:proto.UrlAnswer.Url)
    })
  ,
  'DESCRIPTOR' : _URLANSWER,
  '__module__' : 'conversation_pb2'
  # @@protoc_insertion_point(class_scope:proto.UrlAnswer)
  })
_sym_db.RegisterMessage(UrlAnswer)
_sym_db.RegisterMessage(UrlAnswer.Url)

ConversationLink = _reflection.GeneratedProtocolMessageType('ConversationLink', (_message.Message,), {
  'DESCRIPTOR' : _CONVERSATIONLINK,
  '__module__' : 'conversation_pb2'
  # @@protoc_insertion_point(class_scope:proto.ConversationLink)
  })
_sym_db.RegisterMessage(ConversationLink)

ConversationNode = _reflection.GeneratedProtocolMessageType('ConversationNode', (_message.Message,), {

  'Answer' : _reflection.GeneratedProtocolMessageType('Answer', (_message.Message,), {
    'DESCRIPTOR' : _CONVERSATIONNODE_ANSWER,
    '__module__' : 'conversation_pb2'
    # @@protoc_insertion_point(class_scope:proto.ConversationNode.Answer)
    })
  ,
  'DESCRIPTOR' : _CONVERSATIONNODE,
  '__module__' : 'conversation_pb2'
  # @@protoc_insertion_point(class_scope:proto.ConversationNode)
  })
_sym_db.RegisterMessage(ConversationNode)
_sym_db.RegisterMessage(ConversationNode.Answer)

Conversation = _reflection.GeneratedProtocolMessageType('Conversation', (_message.Message,), {
  'DESCRIPTOR' : _CONVERSATION,
  '__module__' : 'conversation_pb2'
  # @@protoc_insertion_point(class_scope:proto.Conversation)
  })
_sym_db.RegisterMessage(Conversation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _URLANSWER._serialized_start=29
  _URLANSWER._serialized_end=124
  _URLANSWER_URL._serialized_start=91
  _URLANSWER_URL._serialized_end=124
  _CONVERSATIONLINK._serialized_start=126
  _CONVERSATIONLINK._serialized_end=224
  _CONVERSATIONNODE._serialized_start=227
  _CONVERSATIONNODE._serialized_end=434
  _CONVERSATIONNODE_ANSWER._serialized_start=348
  _CONVERSATIONNODE_ANSWER._serialized_end=434
  _CONVERSATION._serialized_start=436
  _CONVERSATION._serialized_end=489
# @@protoc_insertion_point(module_scope)
